### ISSUE TITLE
Multiple download not working as intended

### ISSUE THREAD

**Issue by perigozin** [amydevs/altc-gui#1]
Hello! First of all thanks for this tool, it's exactly what I was looking for.

Just wanted to give you a heads up that when batch converting multiple themes and clicking the "download all" button at the top, I get the original versions of the files. The convertion works correctly but then I have to click on each of the respective download buttons in order to get the correct versions.

**Comment by amydevs** [comment]
Thanks a bunch! Turns out i had accidentally bound the wrong data for the download all click handler lol, should be fixed now as soon as CI deploys it (ctrl-f5 refresh page in case the your browser is still showing the cached version)

**Comment by perigozin** [comment]
No problem! Thanks for the quick fix

**Comment by amydevs** [comment]
Np! Glad to help 👍
